framework:
    workflows:
        order_complete:
            type: state_machine
            supports:
                - App\Entity\WorkflowEntry
            marking_store:
                type: 'method'
                property: 'currentState'
            places:
                - initialised
                - verified
                - confirmed
                - completed
            transitions:
                verify_order:
                    from: initialised
                    to: verified
                confirm_order:
                    from: verified
                    to: confirmed
                complete_order:
                    from: confirmed
                    to: completed

