framework:
    workflows:
        order_send:
            type: state_machine
            supports:
                - App\Entity\WorkflowEntry
            marking_store:
                type: 'method'
                property: 'currentState'
            places:
                - initialised
                - verified
                - approved
                - sent_to_email
                - marked_as_sent
            transitions:
                verify_order:
                    from: initialised
                    to: verified
                approve_order:
                    from: verified
                    to: approved
                send_order_to_email:
                    from: approved
                    to: sent_to_email
                mark_order_as_sent:
                  from: sent_to_email
                  to: marked_as_sent

